#!/usr/bin/env python3
"""
修正 spark_java_api_高质量完整文档.md 中的问题：
1. 删除重复的方法行
2. 为空白示例补充内容
3. 为不清晰描述（"xxx方法"）补充清晰描述
"""

import re

# 方法名推断描述规则
METHOD_DESC_RULES = {
    # 常见动词
    'get': '获取',
    'set': '设置',
    'create': '创建',
    'build': '构建',
    'add': '添加',
    'remove': '移除',
    'delete': '删除',
    'drop': '删除/丢弃',
    'load': '加载',
    'save': '保存',
    'write': '写入',
    'read': '读取',
    'append': '追加',
    'insert': '插入',
    'update': '更新',
    'alter': '修改',
    'find': '查找',
    'search': '搜索',
    'check': '检查',
    'validate': '校验',
    'verify': '验证',
    'compute': '计算',
    'calculate': '计算',
    'count': '计数',
    'aggregate': '聚合',
    'merge': '合并',
    'split': '拆分',
    'convert': '转换',
    'transform': '转换',
    'map': '映射',
    'filter': '过滤',
    'sort': '排序',
    'order': '排序',
    'group': '分组',
    'join': '连接',
    'union': '合并',
    'intersect': '交集',
    'subtract': '差集',
    'cache': '缓存',
    'persist': '持久化',
    'unpersist': '取消持久化',
    'close': '关闭',
    'open': '打开',
    'init': '初始化',
    'initialize': '初始化',
    'start': '启动',
    'stop': '停止',
    'begin': '开始',
    'end': '结束',
    'finish': '完成',
    'complete': '完成',
    'execute': '执行',
    'run': '运行',
    'process': '处理',
    'handle': '处理',
    'apply': '应用',
    'register': '注册',
    'unregister': '取消注册',
    'bind': '绑定',
    'unbind': '解绑',
    'lock': '锁定',
    'unlock': '解锁',
    'acquire': '获取/分配',
    'release': '释放',
    'allocate': '分配',
    'deallocate': '释放',
    'clear': '清除',
    'reset': '重置',
    'refresh': '刷新',
    'invalidate': '失效',
    'flush': '刷新',
    'copy': '复制',
    'clone': '克隆',
    'equal': '判断相等',
    'compare': '比较',
    'contains': '包含',
    'has': '检查是否存在',
    'is': '判断是否',
    'can': '判断能否',
    'should': '判断是否应该',
    'must': '必须',
    'need': '需要',
    'require': '要求',
    'allow': '允许',
    'enable': '启用',
    'disable': '禁用',
    'support': '支持',
    'accept': '接受',
    'reject': '拒绝',
    'parse': '解析',
    'format': '格式化',
    'encode': '编码',
    'decode': '解码',
    'serialize': '序列化',
    'deserialize': '反序列化',
    'compress': '压缩',
    'decompress': '解压缩',
    'encrypt': '加密',
    'decrypt': '解密',
    'hash': '哈希计算',
    'digest': '摘要',
    'sign': '签名',
    'verify': '验证',
    'export': '导出',
    'import': '导入',
    'export': '导出',
    'print': '打印',
    'log': '日志',
    'trace': '追踪',
    'debug': '调试',
    'monitor': '监控',
    'watch': '监听',
    'listen': '监听',
    'notify': '通知',
    'trigger': '触发',
    'fire': '触发',
    'emit': '发射/发送',
    'broadcast': '广播',
    'send': '发送',
    'receive': '接收',
    'connect': '连接',
    'disconnect': '断开连接',
    'reconnect': '重连',
    'establish': '建立',
    'destroy': '销毁',
    'dispose': '释放',
    'finalize': '终结',
    'shutdown': '关闭',
    'abort': '中止',
    'cancel': '取消',
    'suspend': '暂停',
    'resume': '恢复',
    'pause': '暂停',
    'wait': '等待',
    'sleep': '休眠',
    'wake': '唤醒',
    'yield': '让步',
    'schedule': '调度',
    'dispatch': '分发',
    'forward': '转发',
    'redirect': '重定向',
    'route': '路由',
    'invoke': '调用',
    'call': '调用',
    'execute': '执行',
    'perform': '执行',
    'do': '执行',
    'make': '创建',
    'produce': '生产',
    'consume': '消费',
    'supply': '提供',
    'provide': '提供',
    'offer': '提供',
    'request': '请求',
    'response': '响应',
    'reply': '回复',
    'answer': '回答',
    'query': '查询',
    'fetch': '获取',
    'retrieve': '获取',
    'collect': '收集',
    'gather': '收集',
    'accumulate': '累积',
    'reduce': '归约',
    'fold': '折叠/归约',
    'expand': '展开',
    'extend': '扩展',
    'expand': '扩展',
    'shrink': '收缩',
    'reduce': '减少',
    'minimize': '最小化',
    'maximize': '最大化',
    'optimize': '优化',
    'tune': '调优',
    'adjust': '调整',
    'modify': '修改',
    'change': '改变',
    'update': '更新',
    'replace': '替换',
    'substitute': '替换',
    'swap': '交换',
    'exchange': '交换',
    'transfer': '转移',
    'move': '移动',
    'shift': '移位',
    'rotate': '旋转',
    'scale': '缩放',
    'zoom': '缩放',
    'resize': '调整大小',
    'rewind': '重绕',
    'seek': '定位',
    'skip': '跳过',
    'jump': '跳转',
    'next': '下一个',
    'previous': '上一个',
    'prev': '上一个',
    'first': '第一个',
    'last': '最后一个',
    'head': '头部',
    'tail': '尾部',
    'top': '顶部',
    'bottom': '底部',
    'left': '左边',
    'right': '右边',
    'up': '向上',
    'down': '向下',
    'push': '压入',
    'pop': '弹出',
    'peek': '查看',
    'poll': '轮询',
    'offer': '提供',
    'take': '获取',
    'put': '放入',
    'post': '提交',
    'get': '获取',
    'head': '头部请求',
    'patch': '部分更新',
    'delete': '删除请求',
    'options': '选项',
    'trace': '追踪',
    'bucket': '分桶',
    'column': '列',
    'days': '天数转换',
    'hours': '小时转换',
    'months': '月份转换',
    'years': '年份转换',
    'identity': '身份转换',
    'ordered': '有序分布',
    'unspecified': '未指定分布',
    'rand': '随机',
    'random': '随机',
    'shuffle': '随机打乱',
    'sample': '采样',
    'distinct': '去重',
    'unique': '唯一',
    'deduplicate': '去重',
    'duplicate': '复制',
    'repeat': '重复',
    'iterate': '迭代',
    'loop': '循环',
    'recurse': '递归',
    'traverse': '遍历',
    'walk': '遍历',
    'visit': '访问',
    'explore': '探索',
    'scan': '扫描',
    'search': '搜索',
    'lookup': '查找',
    'refer': '引用',
    'dereference': '解引用',
    'point': '指向',
    'target': '目标',
    'source': '源',
    'destination': '目标',
    'dest': '目标',
    'origin': '原点',
    'base': '基础',
    'root': '根',
    'parent': '父级',
    'child': '子级',
    'children': '子级',
    'sibling': '同级',
    'ancestor': '祖先',
    'descendant': '后代',
    'successor': '后继',
    'predecessor': '前驱',
    'next': '下一个',
    'prev': '上一个',
    'previous': '上一个',
    'following': '后续',
    'leading': '前导',
    'trailing': '尾随',
    'pending': '待处理',
    'running': '运行中',
    'completed': '已完成',
    'failed': '失败',
    'cancelled': '已取消',
    'timeout': '超时',
    'expired': '已过期',
    'valid': '有效',
    'invalid': '无效',
    'available': '可用',
    'unavailable': '不可用',
    'ready': '就绪',
    'busy': '忙碌',
    'idle': '空闲',
    'active': '活跃',
    'inactive': '非活跃',
    'enabled': '已启用',
    'disabled': '已禁用',
    'visible': '可见',
    'hidden': '隐藏',
    'public': '公共',
    'private': '私有',
    'protected': '保护',
    'internal': '内部',
    'external': '外部',
    'local': '本地',
    'remote': '远程',
    'global': '全局',
    'regional': '区域',
    'national': '国家',
    'world': '世界',
    'universal': '通用',
    'common': '通用',
    'general': '通用',
    'specific': '特定',
    'special': '特殊',
    'custom': '自定义',
    'default': '默认',
    'standard': '标准',
    'normal': '正常',
    'regular': '常规',
    'irregular': '不规则',
    'typical': '典型',
    'atypical': '非典型',
    'simple': '简单',
    'complex': '复杂',
    'basic': '基础',
    'advanced': '高级',
    'intermediate': '中级',
    'elementary': '初级',
    'primary': '主要',
    'secondary': '次要',
    'major': '主要',
    'minor': '次要',
    'main': '主要',
    'sub': '子',
    'super': '超',
    'meta': '元',
    'proto': '原型',
    'abstract': '抽象',
    'concrete': '具体',
    'virtual': '虚拟',
    'physical': '物理',
    'logical': '逻辑',
    'temporal': '时间',
    'spatial': '空间',
    'geographical': '地理',
    'geometrical': '几何',
    'mathematical': '数学',
    'statistical': '统计',
    'scientific': '科学',
    'engineering': '工程',
    'technical': '技术',
    'functional': '功能',
    'structural': '结构',
    'behavioral': '行为',
    'operational': '操作',
    'administrative': '管理',
    'management': '管理',
    'control': '控制',
    'regulation': '调节',
    'governance': '治理',
    'policy': '策略',
    'rule': '规则',
    'constraint': '约束',
    'limit': '限制',
    'bound': '边界',
    'range': '范围',
    'scope': '范围',
    'domain': '领域',
    'realm': '领域',
    'world': '世界',
    'universe': '宇宙',
    'space': '空间',
    'time': '时间',
    'duration': '时长',
    'interval': '间隔',
    'period': '周期',
    'epoch': '时代',
    'era': '时期',
    'age': '年龄',
    'generation': '代',
    'version': '版本',
    'revision': '修订',
    'release': '发布',
    'snapshot': '快照',
    'draft': '草稿',
    'final': '最终',
    'stable': '稳定',
    'unstable': '不稳定',
    'deprecated': '已弃用',
    'legacy': '遗留',
    'obsolete': '过时',
    'modern': '现代',
    'traditional': '传统',
    'classical': '经典',
    'contemporary': '当代',
    'historical': '历史',
    'future': '未来',
    'past': '过去',
    'present': '现在',
    'current': '当前',
    'previous': '之前',
    'next': '之后',
    'before': '之前',
    'after': '之后',
    'prior': '优先',
    'posterior': '后验',
    'anterior': '前',
    'post': '后',
    'pre': '前',
    'intra': '内部',
    'extra': '额外',
    'inter': '之间',
    'intra': '之内',
    'multi': '多',
    'uni': '单',
    'bi': '双',
    'tri': '三',
    'quad': '四',
    'penta': '五',
    'hexa': '六',
    'hepta': '七',
    'octa': '八',
    'nona': '九',
    'deca': '十',
    'centi': '百',
    'milli': '千',
    'micro': '微',
    'nano': '纳',
    'pico': '皮',
    'femto': '飞',
    'atto': '阿',
    'kilo': '千',
    'mega': '兆',
    'giga': '吉',
    'tera': '太',
    'peta': '拍',
    'exa': '艾',
    'zetta': '泽',
    'yotta': '尧',
}

def generate_description(method_name):
    """根据方法名自动推断描述"""
    # 特定方法名直接映射
    special_methods = {
        'quote': '对字符串进行引用处理',
        'randStr': '生成随机字符串',
        'validateUTF8String': '校验UTF8字符串有效性',
        'tryValidateUTF8String': '尝试校验UTF8字符串',
        'getSentences': '将文本分割为句子数组',
        'getSparkVersion': '获取Spark版本字符串',
        'isLuhnNumber': '校验Luhn算法数字（信用卡号校验）',
        'bucket': '创建分桶分区转换',
        'column': '创建列引用表达式',
        'days': '将日期转换为天数',
        'hours': '将时间转换为小时数',
        'identity': '创建身份分区转换',
        'months': '将日期转换为月份数',
        'sort': '创建排序表达式',
        'ordered': '创建有序分布',
        'unspecified': '创建未指定分布',
        'getArguments': '获取函数参数说明',
        'getClassName': '获取类名',
        'getDb': '获取数据库名',
        'getDeprecated': '获取弃用说明',
        'getExamples': '获取使用示例',
        'getExtended': '获取扩展说明',
        'getGroup': '获取函数分组',
        'getName': '获取名称',
        'getNote': '获取备注说明',
        'getOriginalExamples': '获取原始示例',
        'getSince': '获取版本信息',
        'getSource': '获取来源',
        'getUsage': '获取使用说明',
        'binaryCompare': '二进制数据比较',
        'binaryEquals': '二进制数据相等判断',
        'binarySearch': '二分查找算法',
        'blankString': '生成空白字符串',
        'arrayEquals': '数组相等判断',
        'arrayHeader': '获取数组头部信息',
        'appendNull': '追加null值到数组',
        'appendBoolean': '追加布尔值到数组',
        'appendBytes': '追加字节到数组',
        'appendCodePoint': '追加Unicode码点到字符串',
        'appendDate': '追加日期到数组',
        'appendDecimal': '追加Decimal到数组',
        'appendDouble': '追加双精度浮点数到数组',
        'appendFloat': '追加单精度浮点数到数组',
        'appendLong': '追加长整数到数组',
        'appendString': '追加字符串到数组',
        'appendTimestamp': '追加时间戳到数组',
        'appendTimestampNtz': '追加无时区时间戳到数组',
        'appendUuid': '追加UUID到数组',
        'appendVariant': '追加Variant类型到数组',
        'appendBinary': '追加二进制数据到数组',
        'addRow': '添加行到批处理',
        'addPrimitiveColumn': '添加原始类型列',
        'addStringColumn': '添加字符串类型列',
        'addFetchRequest': '添加数据获取请求',
        'addRpcRequest': '添加RPC请求',
        'addSparkArg': '添加Spark参数',
        'addPyFile': '添加Python文件',
        'addCustomHeader': '添加自定义请求头',
        'addBin': '添加二进制数据',
        'addAppArgs': '添加应用参数',
        'addKey': '添加键',
        'addStreamCallback': '添加流回调',
        'addToChannel': '添加到通道',
        'addURL': '添加URL',
        'acquireExecutionMemory': '获取执行内存',
        'acquireMemory': '获取内存',
        'allocateArray': '分配数组内存',
        'allocatePage': '分配页面内存',
        'applicationRemoved': '应用移除事件',
        'authEngineVersion': '认证引擎版本',
        'Authenticate': '认证操作',
        'authRTTimeoutMs': '认证超时时间（毫秒）',
        'available': '检查数据是否可用',
        'backLog': '获取待处理日志',
        'acceptInboundMessage': '接受入站消息',
        'abort': '中止操作',
    }
    
    if method_name in special_methods:
        return special_methods[method_name]
    
    # 根据方法名前缀推断
    for prefix, desc in METHOD_DESC_RULES.items():
        if method_name.lower().startswith(prefix.lower()):
            # 提取后缀部分作为主体
            rest = method_name[len(prefix):]
            if rest:
                return f"{desc}{rest}相关功能"
            return f"{desc}相关功能"
    
    # 根据方法名包含关键词推断
    for keyword, desc in METHOD_DESC_RULES.items():
        if keyword.lower() in method_name.lower():
            return f"{desc}相关功能"
    
    # 默认描述
    return f"{method_name}操作"

def generate_example(method_name, params, return_type):
    """根据方法信息生成示例说明"""
    desc = generate_description(method_name)
    
    # 根据参数类型生成简单示例
    if params == '无':
        return f"调用该方法执行{desc}"
    
    return f"传入参数执行{desc}"

def fix_document(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    fixed_lines = []
    prev_content = None
    changes = {'duplicates_removed': 0, 'descriptions_fixed': 0, 'examples_added': 0}
    
    for i, line in enumerate(lines):
        content = line.rstrip('\n')
        
        # 检查是否是重复行
        if content == prev_content and content.startswith('| `'):
            changes['duplicates_removed'] += 1
            continue
        
        # 提取方法名
        match = re.search(r'\| `(\w+)` \|', line)
        if match:
            method_name = match.group(1)
            
            # 提取参数和返回类型用于生成示例
            parts = content.split('|')
            if len(parts) >= 5:
                params = parts[2].strip() if len(parts) > 2 else ''
                return_type = parts[3].strip() if len(parts) > 3 else ''
                
                # 修正描述（"xxx方法"形式）
                old_desc = f'{method_name}方法'
                if old_desc in content:
                    new_desc = generate_description(method_name)
                    line = line.replace(old_desc, new_desc)
                    changes['descriptions_fixed'] += 1
                
                # 补充空白示例
                if line.rstrip().endswith('|  |'):
                    example = generate_example(method_name, params, return_type)
                    line = line.rstrip()
                    line = re.sub(r'\|  \|$', f'| {example} |', line) + '\n'
                    changes['examples_added'] += 1
        
        fixed_lines.append(line)
        prev_content = content
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(fixed_lines)
    
    return changes

if __name__ == '__main__':
    filepath = '/home/h00517772/spark/hyx/spark_java_api_高质量完整文档.md'
    changes = fix_document(filepath)
    print(f"修正完成:")
    print(f"  - 删除重复行: {changes['duplicates_removed']}")
    print(f"  - 修正描述: {changes['descriptions_fixed']}")
    print(f"  - 补充示例: {changes['examples_added']}")